name: flutter_shaders_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  auto_size_text: ^3.0.0
  flutter:
    sdk: flutter
  flutter_shaders: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  custom_lint: ^0.7.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/main_menu/
    - assets/images/color/
    - assets/images/shape/
    - assets/images/matrizes_2d/
    - assets/images/patterns/
    - assets/images/generative_designs/
    - assets/images/noise/
  
  shaders:
    - shaders/color/color_example_1.glsl
    - shaders/color/color_example_2.glsl
    - shaders/color/color_example_3.glsl
    - shaders/color/color_example_4.glsl
    - shaders/color/color_example_5.glsl

    - shaders/shape/shape_example_1.glsl
    - shaders/shape/shape_example_2.glsl
    - shaders/shape/shape_example_3.glsl
    - shaders/shape/shape_example_4.glsl
    - shaders/shape/shape_example_5.glsl
    - shaders/shape/shape_example_6.glsl

    - shaders/matrizes_2d/matrizes_2d_example_1.glsl
    - shaders/matrizes_2d/matrizes_2d_example_2.glsl
    - shaders/matrizes_2d/matrizes_2d_example_3.glsl
    - shaders/matrizes_2d/matrizes_2d_example_4.glsl

    - shaders/patterns/patterns_example_1.glsl
    - shaders/patterns/patterns_example_2.glsl
    - shaders/patterns/patterns_example_3.glsl
    - shaders/patterns/patterns_example_4.glsl
    - shaders/patterns/patterns_example_5.glsl

    - shaders/generative_designs/generative_designs_example_1.glsl
    - shaders/generative_designs/generative_designs_example_2.glsl
    - shaders/generative_designs/generative_designs_example_3.glsl
    - shaders/generative_designs/generative_designs_example_4.glsl
    - shaders/generative_designs/generative_designs_example_5.glsl

    - shaders/noise/noise_example_1.glsl
    - shaders/noise/noise_example_2.glsl
    - shaders/noise/noise_example_3.glsl